### ISSUE TITLE
Client to client communication sample

### ISSUE THREAD

**Issue by sensboston** [cactuaroid/GrpcWpfSample#6]
Thanks for the good sample! Could you please provide a snippet for client to client communication via server? I mean, something like a "direct chatting" between clients?

**Comment by cactuaroid** [comment]
What I want to show in this repository is how to implement unary call and server-side streaming.

One of the simple design for client to client communication is similar to my sample. In my sample, server stores all chat logs but you also can simply forward to another client. In this case, `Write` and `Subscribe` methods requires additional parameter, destination client id and subscriber client id respectively. Server shall hold `responseStream` for each client id when `Subscribe` is called, then `Write` method can write the message to one of the `responseStream` identified by client id.
